Controllers films users
Scandi7/java-filmorate pull request #3
Opened 2024-08-24 12:28 UTC by Scandi7

2024-08-25 15:26 UTC, EugeneLenkevich requested changes
Привет, Даниил! Спасибо за PR.

Отличная работа! :)
В первую очередь проверь, пожалуйста, аннотацию @Data ну и еще пара моментов  по мелочи если времени хватит

2024-08-25 15:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (film.getName() == null || film.getName().isEmpty()) {
film.getName() == null || film.getName().isEmpty()

Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2024-08-25 15:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidationException ex) {
Не обязательно руками ставить в соответствие статусы сообщениям, можно прикрутить например ControllerAdvice :)

https://habr.com/ru/articles/528116/

2024-08-25 15:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
С этой аннотацией надо поаккурантей. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения бдут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. лучше или переопределить руками или указать через аннотации как генерировать эти методы :)

2024-08-25 19:04 UTC, Scandi7 commented
> Привет, Даниил! Спасибо за PR.
> 
> Отличная работа! :) В первую очередь проверь, пожалуйста, аннотацию @DaTa ну и еще пара моментов по мелочи если времени хватит

Привет, Евгений. И вам спасибо за ревью. Аннотацию @Data убрал. Вообще она изначально была в шаблоне проекта и я как то не задумывался и вообще не знал о таких моментах. Полезная информация, спасибо. А по поводу других комментариев, прочитаю и применю это попозже, я так понимаю как то критически это не влияет, просто улучшение кода.

2024-08-26 09:19 UTC, EugeneLenkevich approved these changes
Ох уж эти шаблоны

Можно было не выпиливать вовсе аннотацию а ручками или с помощью аннотаций задать equals и hashCode, все таки лишнего кода было бы поменьше.  :)

2024-08-26 09:24 UTC, merged