добавлена схема бд.
Scandi7/java-filmorate pull request #7
Opened 2024-09-24 12:21 UTC by Scandi7

добавлена бд
добавлен dao для User

2024-09-27 08:29 UTC, EugeneLenkevich requested changes
Привет, Даниил! Спасибо за PR.

Да, отличная работа, приятно смотреть код, но давай все таки сделаем сервисы для жанров и пр, иначе у нас логика в контроллерах, а это считается антипаттерном. На самом деле в реальной жизни иногда так делают для каких то справочников чтобы кода было поменьше. Но мы так в учебном то проекте не будем :)

2024-09-27 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        return genreStorage.getAllGenres().stream()
Давай все таки не будем пихать логику в контроллер, а сделаем полноценный сервис. Контроллер только маршрутизирует запросы в требуемые сервисы, лучше чтобы в нем не было логики, иначе у нас может не быть единообразия работы логики если сервис будет вызываться в других местах :)

И сразу второй момоент, мы выгружаем все записи из хранилища и стримом берем первые n-записей. Это не особо эффективно и опасно так как таблица может в какой то день стать очень большой и у нас закончится память, например. Тут лучше на уровне хранилища сделать метод с соответствующим параметром и уже там запросом к БД отобрать нужное количество данных. Плюс так еще и будет более правильно с точки зрения распределения обязанностей, ниже выжимку приведу 

По классике обязанности распределяются вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2024-09-27 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +                .orElseThrow(() -> new NotFoundException("Жанр с id " + id + " не найден"));
Опять таки это тоже логика в контроллере, ее место в сервисе :)

2024-09-27 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaRatingController.java
> +        return mpaRatingStorage.getAllMpa().stream()
И тут аналогично комментариям выше

2024-09-27 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        if (genres.isEmpty()) {
Интересно, а будет ли работать если этот код и ниже заменить на :) 

return genres.stream().findFirst();

2024-09-27 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public abstract class InMemoryUserStorage implements UserStorage {
Вообще, чтобы не мешались in-memory реализации можно вовсе выпилить, если что в гите, в истории, они сохраняться :)

2024-09-28 05:27 UTC, Scandi7 commented
> Привет, Даниил! Спасибо за PR.
> 
> Да, отличная работа, приятно смотреть код, но давай все таки сделаем сервисы для жанров и пр, иначе у нас логика в контроллерах, а это считается антипаттерном. На самом деле в реальной жизни иногда так делают для каких то справочников чтобы кода было поменьше. Но мы так в учебном то проекте не будем :)

Привет, Евгений, и вам спасибо за ревью)

2024-09-28 08:33 UTC, EugeneLenkevich approved these changes
Во, супер, спасибо :)

2024-10-02 20:07 UTC, merged